# Generated by Django 5.1.5 on 2025-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('tijdstip', models.TimeField()),
                ('omschrijving', models.CharField(max_length=200)),
                ('kosten', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
